### ISSUE TITLE
Sorting in Dashboard

### ISSUE THREAD

**Issue by AlanSwenson** [aclark4life/aclarknet-best-pro#3]
The sorting in the Dashboard only sorts the `viewable` results on that page.  

ex.  If you sort by date ascending and the earliest date happens to be on page 2 the first result will only be the earliest date that already exists on page 1.  It will not pull anything from any other pages into the sort.

**Comment by aclark4life** [comment]
@AlanSwenson @wiredfool This is potentially a "feature" since I'm not sure how … well, OK I guess I can see a way to fix it "for real":

- E.g. Given 1000 entries paginated at 100 a page, and given the constraints of ``Paginator`` … somehow figure out a way to load all 1000 entries but only display 100 until someone tries to sort, at which point AJAX reload the first 100 results with all 1000 entries considered … right?

In the meantime, you can work around this by ditching pagination with the "show all" button then sorting works as expected:

<img width="1172" alt="Screen Shot 2019-08-07 at 8 06 24 AM" src="https://user-images.githubusercontent.com/72164/62621826-e4ae5880-b8ea-11e9-94a3-5d461dcbb96d.png">
<img width="1153" alt="Screen Shot 2019-08-07 at 8 06 36 AM" src="https://user-images.githubusercontent.com/72164/62621827-e4ae5880-b8ea-11e9-983a-36f5e645a21b.png">
<img width="1197" alt="Screen Shot 2019-08-07 at 8 06 52 AM" src="https://user-images.githubusercontent.com/72164/62621828-e4ae5880-b8ea-11e9-9366-51ae8ebfa307.png">

**Comment by AlanSwenson** [comment]
@aclark4life thats cool, is it possible then to have the default for the data load in to be date descending (aka newest first) instead of id#?  I basically was only sorting it to make sure my most recent entry was in correctly and not doubled up or anything.

**Comment by aclark4life** [comment]
@AlanSwenson Can you add a screenshot? As far as I can tell that's already the case …

**Comment by AlanSwenson** [comment]
Since it's a new month, I dont have 20 entries yet so it doesn't loop over
to the next page, so ill screen shot it at the end of the month. :)

**Comment by aclark4life** [comment]
Reopen whenever you can screenshot
